### ISSUE TITLE
Error status 502: Request failed

### ISSUE THREAD

**Issue by whosbad19** [djmango/obsidian-transcription#57]
Hey, i was unable to transcribe any vocal notes today. i keep getting this error message when i tried to transcribe a note. Can someone help me with this issue please?
![captuuure](https://github.com/djmango/obsidian-transcription/assets/154232900/1520a273-b544-408c-bb71-b8541a1c3ab6)

**Comment by djmango** [comment]
Resolved!

**Comment by whosbad19** [comment]
Hey, i still have the same issue but now it's showing error status 500. Can you please check this? thx

![captuuure](https://github.com/djmango/obsidian-transcription/assets/154232900/103a17bb-930d-4f8f-9ec5-651a424882a7)

**Comment by djmango** [comment]
Hmm apologies, looks like theres downtime spurring every few hours - I'm going to talk with our service providers to find the root cause, and have implemented a workaround this morning. Should be working now, let know if the problem reoccurs

**Comment by whosbad19** [comment]
@djmango Hey, it's been working but today once again i got the 502 error. Can you check that please?

**Comment by djmango** [comment]
Should be resolved! Keep me posted, good that the issue is less common now.. will continue working to eliminate it entirely

**Comment by aikruger** [comment]
I keep on getting this error yesterday and today

**Comment by djmango** [comment]
Are you still experiencing it?

**Comment by xianleonard** [comment]
Hey @djmango, sorry to bump this again, but I've still been getting the 502 error this week. Any chance you'd be able to look into it? Thanks so much for your work on this plugin!

**Comment by Hussain004** [comment]
Hello @djmango, the "Error transcribing file: Error: Request failed status 500" error is back. The audio notes gets correctly transcribed on swiftink.io but shows this error in Obsidian.  Any chance it can be fixed? Awesome plugin btw.

**Comment by djmango** [comment]
Swiftink is shut down
